### ISSUE TITLE
Pulsar Host going offline

### ISSUE THREAD

**Issue by Daxten** [sksamuel/pulsar4s#11]
Hey, great library!

When the pulsar host becomes unavailable, the following exception is thrown:

`java.lang.NoClassDefFoundError: org/apache/pulsar/shade/io/netty/util/concurrent/DefaultPromise$1`

which seems strange :)
Also is there another way to detect a connection closing (some kind of callback maybe?)

**Comment by sksamuel** [comment]
Anymore to the stack trace ?

**Comment by Daxten** [comment]
Ah sure sorry
```
Exception in thread "pulsar-client-io-1-1" java.lang.NoClassDefFoundError: org/apache/pulsar/shade/io/netty/util/concurrent/DefaultPromise$1
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:925)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise$1
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
```

**Comment by sksamuel** [comment]
Try adding pulsar-common or pulsar-admin to your classpath. If that fixes it I'll include them in the release pom.

**Comment by Daxten** [comment]
Will try that!

Is catching an exception the right way to handle the client disconnecting or is there another way?

**Comment by Daxten** [comment]
adding `libraryDependencies += "org.apache.pulsar" % "pulsar-common" % "2.1.1-incubating",` fixed it, it will now also auto-reconnect

**Comment by sksamuel** [comment]
Yes I will release today I think, master is on 2.2 if that's ok.

**Comment by Daxten** [comment]
Yes ofc

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by sksamuel** [comment]
2.3.0 is released.
