### ISSUE TITLE
Akka streams consumer hangs if failure during prestart

### ISSUE THREAD

**Issue by lukestephenson** [sksamuel/pulsar4s#184]
Noticed this when the cluster was not in a healthy state.  The exception was logged to stderr, I assume by akka streams.  It was not propagated to the containing application to deal with.

After this the application hung and did not consume any further messages from pulsar.

When we run the stream, we get back a `Control`, but that does not expose any ability to monitor if it completes or fails.

```
org.apache.pulsar.client.api.PulsarClientException$LookupException: Failed to subscribe persistent://tenant1/test/topic with 64 partitions
Namespace bundle for topic (persistent://tenant1/test/topic-partition-1) not served by this instance. Please redo the lookup. Request is denied: namespace=tenant1/test
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:677)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:99)
	at com.sksamuel.pulsar4s.DefaultPulsarClient.consumer(PulsarClient.scala:190)
	at com.zendesk.pulsar.test.pulsar.PulsarConsumer.makeConsumer(PulsarConsumer.scala:65)
	at com.zendesk.pulsar.test.pulsar.PulsarConsumer.$anonfun$run$3(PulsarConsumer.scala:24)
	at com.sksamuel.pulsar4s.akka.streams.PulsarSourceGraphStage$$anon$1.preStart(PulsarSourceGraphStage.scala:80)
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:292)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:575)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:682)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:731)
	at akka.actor.Actor.aroundPreStart(Actor.scala:550)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:550)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.create(ActorCell.scala:678)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:549)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:571)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by gmethvin** [comment]
Are you interested in submitting a PR to fix this? I think the correct behavior should be to fail the stage.

**Comment by lukestephenson** [comment]
@gmethvin I'm unlikely to submit a PR to fix at this point. I'm not actively working on pulsar related things now. And if I pick this up again, I think I'd be likely to use Monix Observable rather than akka streams.
